//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int Eno { get; set; }
        public string Ename { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Depno { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
